# Generated by Django 5.2.7 on 2025-10-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='curso',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
