# Generated by Django 5.2.7 on 2025-10-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_aluno_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('idade', models.IntegerField()),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('telefone', models.CharField(blank=True, max_length=16, null=True)),
                ('codigo_ef', models.CharField(max_length=7)),
            ],
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='curso',
        ),
        migrations.AddField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='plano',
            field=models.CharField(blank=True, choices=[('BASICO', 'Básico'), ('PREMIUM', 'Premium'), ('VIP', 'VIP')], max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='telefone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
